### ISSUE TITLE
Problème dans l'ajout des nouvelles métriques p2v

### ISSUE THREAD

**Issue by yboursin** [gustaveroussy/pileup2vcf#2]
J'utilise votre script pileup2vcf afin de convertir mon fichier pileup en vcf et de trier les variants.
En testant différents paramètres, j'ai remarqué que lorsque que j'augmente le paramètre minReadQuality, le nombre de variants candidats augmente aussi alors qu'il devrait diminuer d'après les explications fournies dans le help.
Par exemple, avec minReadQualityCov=1 :
    si minReadQuality=5 -> 0 variant,
    si minReadQuality=25 -> 40024 variants.

En regardant dans votre script, j'ai vu que dans Variants.py, la fonction computeMinReadQuality ajoute +1 au nombre de lectures lorsque sa qualité est inférieure à minReadQuality.
Est-ce normal ?

**Comment by mlebeur** [comment]
Le problème est corrigé. La modification concerne les fonctions de calcul de la qualité dans GenoPy/Variants.py.
